// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/judge.proto

package judge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId   string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`       // Уникальный ID отправки (UUID как строка)
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // ID пользователя (UUID как строка)
	TaskId         string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                         // ID задачи (UUID как строка)
	Code           string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`                                           // Исходный код решения (строка)
	Lang           string                 `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`                                           // Язык программирования (e.g., "cpp", "java", "python", "kotlin", "go", "rust", "js")
	Input          []string               `protobuf:"bytes,6,rep,name=input,proto3" json:"input,omitempty"`                                         // Входные данные для теста (строка, возможно многострочная)
	TimeLimitMs    int32                  `protobuf:"varint,7,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`       // Лимит времени в миллисекундах (e.g., 1000 для 1 секунды)
	MemoryLimitMb  int32                  `protobuf:"varint,8,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"` // Лимит памяти в мегабайтах (e.g., 256)
	AdditionalArgs []string               `protobuf:"bytes,9,rep,name=additional_args,json=additionalArgs,proto3" json:"additional_args,omitempty"` // Опционально: дополнительные флаги компиляции/запуска (e.g., для C++: "-O2")
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_judge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_judge_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *ExecuteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecuteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ExecuteRequest) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteRequest) GetTimeLimitMs() int32 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

func (x *ExecuteRequest) GetMemoryLimitMb() int32 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

func (x *ExecuteRequest) GetAdditionalArgs() []string {
	if x != nil {
		return x.AdditionalArgs
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []string               `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`                                           // Массив выводов (по одному на input)
	Stderr        []string               `protobuf:"bytes,2,rep,name=stderr,proto3" json:"stderr,omitempty"`                                           // Массив ошибок
	TimeUsedSec   []float64              `protobuf:"fixed64,3,rep,packed,name=time_used_sec,json=timeUsedSec,proto3" json:"time_used_sec,omitempty"`   // Массив времён
	MemoryUsedKb  []int32                `protobuf:"varint,4,rep,packed,name=memory_used_kb,json=memoryUsedKb,proto3" json:"memory_used_kb,omitempty"` // Массив памяти
	ExitCode      []int32                `protobuf:"varint,5,rep,packed,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`               // Массив кодов выхода
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`           // Общая ошибка (if any)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_judge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_judge_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetOutput() []string {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteResponse) GetStderr() []string {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecuteResponse) GetTimeUsedSec() []float64 {
	if x != nil {
		return x.TimeUsedSec
	}
	return nil
}

func (x *ExecuteResponse) GetMemoryUsedKb() []int32 {
	if x != nil {
		return x.MemoryUsedKb
	}
	return nil
}

func (x *ExecuteResponse) GetExitCode() []int32 {
	if x != nil {
		return x.ExitCode
	}
	return nil
}

func (x *ExecuteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_judge_proto protoreflect.FileDescriptor

const file_proto_judge_proto_rawDesc = "" +
	"\n" +
	"\x11proto/judge.proto\x12\x05judge\"\x9a\x02\n" +
	"\x0eExecuteRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x12\n" +
	"\x04lang\x18\x05 \x01(\tR\x04lang\x12\x14\n" +
	"\x05input\x18\x06 \x03(\tR\x05input\x12\"\n" +
	"\rtime_limit_ms\x18\a \x01(\x05R\vtimeLimitMs\x12&\n" +
	"\x0fmemory_limit_mb\x18\b \x01(\x05R\rmemoryLimitMb\x12'\n" +
	"\x0fadditional_args\x18\t \x03(\tR\x0eadditionalArgs\"\xcd\x01\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06output\x18\x01 \x03(\tR\x06output\x12\x16\n" +
	"\x06stderr\x18\x02 \x03(\tR\x06stderr\x12\"\n" +
	"\rtime_used_sec\x18\x03 \x03(\x01R\vtimeUsedSec\x12$\n" +
	"\x0ememory_used_kb\x18\x04 \x03(\x05R\fmemoryUsedKb\x12\x1b\n" +
	"\texit_code\x18\x05 \x03(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage2K\n" +
	"\x0fExecutorService\x128\n" +
	"\aExecute\x12\x15.judge.ExecuteRequest\x1a\x16.judge.ExecuteResponseB\x0fZ\r./proto;judgeb\x06proto3"

var (
	file_proto_judge_proto_rawDescOnce sync.Once
	file_proto_judge_proto_rawDescData []byte
)

func file_proto_judge_proto_rawDescGZIP() []byte {
	file_proto_judge_proto_rawDescOnce.Do(func() {
		file_proto_judge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_judge_proto_rawDesc), len(file_proto_judge_proto_rawDesc)))
	})
	return file_proto_judge_proto_rawDescData
}

var file_proto_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_judge_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: judge.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: judge.ExecuteResponse
}
var file_proto_judge_proto_depIdxs = []int32{
	0, // 0: judge.ExecutorService.Execute:input_type -> judge.ExecuteRequest
	1, // 1: judge.ExecutorService.Execute:output_type -> judge.ExecuteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_judge_proto_init() }
func file_proto_judge_proto_init() {
	if File_proto_judge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_judge_proto_rawDesc), len(file_proto_judge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_judge_proto_goTypes,
		DependencyIndexes: file_proto_judge_proto_depIdxs,
		MessageInfos:      file_proto_judge_proto_msgTypes,
	}.Build()
	File_proto_judge_proto = out.File
	file_proto_judge_proto_goTypes = nil
	file_proto_judge_proto_depIdxs = nil
}
